### ISSUE TITLE
Insane lag casued by MoneyFromMobs

### ISSUE THREAD

**Issue by bakedpotato132** [chocolf/MoneyFromMobs#15]
![image](https://user-images.githubusercontent.com/102444850/164352435-be8ddf39-7db7-49e0-b2b4-5f4f8bc7708f.png)

Why is the update checker using 12% of tick?

**Comment by chocolf** [comment]
To check for an update the plugin must connect to the Spigot website so Spigot must have been recieving a lot of connections at that time causing the response to take longer, but thank you for letting me know I'll see if theres something I can do to maybe timeout the connection if it is taking too long.

For now you can disable the update checker in the config on line 2
