### ISSUE TITLE
Bug report MoneyFromMobs

### ISSUE THREAD

**Issue by pupshadow** [chocolf/MoneyFromMobs#2]
I think this issue forms when there is a custom mob with Mythicmobs.

Error attached: https://pastebin.com/iAh1nexh

PaperMC is what I'm running.

Version: 

Plugin MoneyFromMobs v3.71

Plugin list:

Plugins (52): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, ClearLag, CMI, CMILib, CoreProtect, DeadChest, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Holograms, Lands, LevelledMobs, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicLib, MythicMobs, MythicMobsExtension, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, ShatteredCore, ShatteredScrolls, SkinsRestorer, StaffFacilities, TreeAssist, Vault, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

**Comment by SmallSansSerif** [comment]
Also see a similar error:

https://pastebin.com/UCLE6fdn

**Comment by chocolf** [comment]
Hey, this should be fixed in the latest update. It was something to do with moving the floating text message upwards asynchronously instead of synchronously. I was trying to save server resources but I guess it has to be done in the main thread.
