### ISSUE TITLE
money drop particle can’t clear

### ISSUE THREAD

**Issue by TimmyYue** [chocolf/MoneyFromMobs#21]
I restart server, but it still stay there, can fix it?

**Comment by chocolf** [comment]
Yes, if you stand right next to it and type /mfmclear it should go

**Comment by TimmyYue** [comment]
I enter this command,but still have questions 
![5CE617B4-8BE5-4015-A797-53F99D44BE17](https://user-images.githubusercontent.com/77110709/222958173-ee70a71f-299c-4a4f-90b5-1bc9532e247c.jpeg)

**Comment by chocolf** [comment]
You need to stand right next to them

**Comment by TimmyYue** [comment]
only have particle ,don’t have coin , I also try stand right to them but same

**Comment by chocolf** [comment]
/minecraft:kill @e[type=armor_stand,distance=..20]
try using that
