### ISSUE TITLE
MoneyFromMobs plugin

### ISSUE THREAD

**Issue by CubiTub** [chocolf/MoneyFromMobs#5]
A short but important issue which is crucial .
The plugin works wonders really good plugin , But when killing a player I don't want the "Killed" player to lose money and vice versa, I just want it to be like a regular kill and get money (Like mobs) [And I know it could be a money machine that player can use but I don't mind it]
Lets say:
When killing a player the "killed" player doesn't receive money nor he loses money and the "Killer" is getting the money that I set it to be (say 100$)
Is there a way to set it like that ?

**Comment by chocolf** [comment]
Hey, Sorry for the really long wait but this has been added in the latest update
