### ISSUE TITLE
2 Suggestions about integration.

### ISSUE THREAD

**Issue by AlternativeSoap** [chocolf/MoneyFromMobs#6]
Leveledmobs:
Multiplier when it's a higher level mob. More money drops. 

InfernalMobs:
When a mob is turning infernal it should double up rewards or also give it multipliers.

To both of those:
Permissions with multipliers so it's possible to give higher ranks better chance for money drops and give more moneys.

**Comment by chocolf** [comment]
Both Added in latest update! :)
