### ISSUE TITLE
Fractional numbers unusable

### ISSUE THREAD

**Issue by TheJavick** [chocolf/MoneyFromMobs#8]
Only integers can be used in the MFM plugin.

When i try to substitute a fractional number for example such as 1.5 only $ 1 falls. If you try to substitute the number less than one currency stops falling out at all. And the problem is not with commas or periods.

Server parameters:
Game version: 1.16.5.
Server core: PaperSpigot.
Server core and game version: paper version of git-Paper-788 (MC: 1.16.5) (implementation of API version 1.16.5-R0.1-SNAPSHOT).

**Comment by chocolf** [comment]
Hey, you need to set the RandomIntegerOnly option in the config to false. Should be near line 37:
```
# If the random number between the set Min and Max for a mob should be a random whole number or a random number to 2 decimal places.
RandomIntegerOnly: false
```

**Comment by TheJavick** [comment]
Oh, I'm sorry. You're right, everything works now.
